#!/bin/bash
if [[ $# -ne 3 ]]; then
  echo "Syntax: jenkins_orb <project> <fail color> <pass color>"
  exit 1
fi

TMPFILE=`mktemp /tmp/jenkins_orb.XXXXX`
curl -s http://of1-dev-ci/job/$1/rssAll > $TMPFILE
STATUS=`/home/paul/src-external/xml2json/xml2json.py -t xml2json $TMPFILE | sed 's/{http:\/\/www.w3.org\/2005\/Atom}//g' | jq -r '.feed.entry[0].title'`
rm $TMPFILE
if [[ $STATUS =~ broken ]]; then
  echo $2
else
  echo $3
fi

